/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("application")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

javafx {
    version = "22-ea+16"  // ou a versão mais recente disponível
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.graphics")
}

application {
    // Define the main class for the application.
    mainClass.set("app.App")
}
dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.8.2")

    implementation("com.google.guava:guava:32.1.1-jre")

    // JavaFX for Graphic Interface
    implementation("org.openjfx:javafx:22-ea+16")
    // SQLite for local database
    implementation("org.xerial:sqlite-jdbc:3.44.1.0")
    // Jackson for manipulate JSON archives
    implementation("com.fasterxml.jackson.core:jackson-databind:2.16.0")
    // https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation("org.slf4j:slf4j-api:2.0.9")
}


